import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster"
import HoverHighlightWrapper from "@/components/wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "max-w-xl m-auto mt-8")}>
        <div className="flex flex-row flex-1 align-middle justify-center"><Header /></div>
        <Toaster />
        <HoverHighlightWrapper>
          {children}
        </HoverHighlightWrapper>
      </body>
    </html>
  );
}
